### ISSUE TITLE
Simpler Hacks

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/inline-style-prefixer#10]
We should embrace a more modular, clean, simple and straight forward method to define hacks.
E.g. just a plain object with the affected key, an optional condition and of course a callback function which provides both key and value as well as the whole style object.

This would also simplify the act of testing each special hack.

**Comment by rofrischmann** [comment]
The following settings should be enough to fully describe a hack:

```javascript
const hack = {
   key: 'calc', // Property/Value to identify the hack
   conidition: browser.android && browser.version < 4.4, // special condition when to use this hack
   fn = (property, value, styles) => {
      styles[property] = value.replace('calc', '-webkit-calc') 
   },
   options: { // additional options
      contains: true // value contains key (not equals)
   }
} 
```

**Comment by ianobermiller** [comment]
You might consider simplifying the API even further, to a function that takes a style object and returns a style object. There are some "hacks" that are only applicable when a combination of styles are present, and this gives the most flexibility with the simplest API. Additionally, you should pass in the other things a hack should expect to have access to, like browser:

```js
function calcPlugin(style, browser) {
  if (!browser.android || browser.version > 4.4) {
    return style;
  }

  return Object.keys(style, 
    (newStyle, key) => {
      newStyle[key] = style[key].replace('calc', '-webkit-calc');
      return newStyle;
    },
    {}
  );
}
```

For value hacks, you could provide a `mapObject` helper:


```js
function calcPlugin(style, {browser, mapObject}) {
  if (!browser.android || browser.version > 4.4) {
    return style;
  }

  return mapObject(
    style, 
    value => value.replace('calc', '-webkit-calc')
  );
}
```

Also, you might want to reconsider the name "hack", and call these "plugins" instead, which is a much more widely accepted term.

**Comment by rofrischmann** [comment]
The renaming sounds fine, while I just took that term hack from autoprefixer. But with the syntax defined above you would iterate the whole object within every plugin.

@ianobermiller I thought it would be better to only iterate it once, but resolve the plugins on each represent key/value given.
I created a small test sample and it seems to work quite well using sth. like this:

```javascript
export default {
  property: 'display',
  value: ['flex', 'inline-flex'],
  condition: ({browser, version}) => {
    return /* long browser-version matching expression */
    },
    fn: ({value, info}) => {
      value = [info.prefix.CSS + value, value]
    }
  }
```

Using the condition while generating the required props / plugins allows me to prefilter those => I only need to apply/iterate those plugins actually needed.

**Comment by rofrischmann** [comment]
Do you think it is important to have some kind of plugin system with which users can add custom plugins? As the goal of this project is to "only" automate the "standard" differences / prefix issues, I can't think of any use case this being benefical. 

I would rather keep this within the code itself and let ppl perhaps send pull request if I miss something.

**Comment by ianobermiller** [comment]
Only thing I can think of is that some hacks (e.g. linear-gradient) might take a good amount of code, and people who don't use it shouldn't have to include it. Unless the code size is in the KB range, I doubt this will be an issue though.

**Comment by rofrischmann** [comment]
Hmm yeah, dunno I kind of like the idea of just having a function as a plugin, but I don't get over the imagination that this might cause loss of performance with bigger style objects.
If you can counter that I might consider creating such a simple API

**Comment by ianobermiller** [comment]
So your proposed API, in Flow types (with some slight renames):

```
export type StyleHack = {
  property: string,
  value: Array<string>,
  isApplicable: (browser: Browser) => bool,
  getValue: (originalValue: string, config: {prefix: string}) => string,
};
```

Looks fine to me (with more explicit names). But how would you specify, for example, the calc hack?

**Comment by rofrischmann** [comment]
Well, isApplicable sounds nice, but getValue might not match all the time since I sometimes modify multi values (e.g. `flexDirection: column-reverse` gets both `WebkitBoxOrient: vertical` and `WebkitBoxDirection: reverse`).

According the calc hack:
I thought about leaving the property at all which then leads to adding it as something like a "global" plugin, that must get checked on every value (can't think of any other hack that needs global state by now). Alternatively we could sort out all props supporting the calc, but this might get kind of a big array :D

Maybe I will try some performance tests if this extra iterating even takes in count something noticeable. If not I am totally in with the function idea.

**Comment by rofrischmann** [comment]
Your proposal in mind I can think of something like this:
Don't know if there is any usecase for `config.browser`, but 
```javascript
// type Browser => whole browserinfo object as bowser returns it
// also contains prefix (CSS, inline) as well as browser which represents the name used for the caniuse database (chrome, safari, opera, ie, firefox, ios_saf, ie_mob, op_mini, and_chr, and_uc, android)

export type StyleHack = {
  isApplicable: (
     browser: Browser
  ) => bool;

  propertyName: string || Array≤string≥; 
  value: string || Array≤string≥; 

  apply: (
    originalPropertyName: string, 
    originalValue: string,
    browser: Browser
  ) => Object; // key-value pairs as property-value
};

With an object outputed we can easily use Object.assign to apply those and do not need to loop the array once again.
Also I'd like to separate the isApplicable to be able to prefilter all plugins.
Also having just an array of propertyNames and (optional) specific values, will help to keep the code as small as possible, as we only need to parse those once.

**Comment by ianobermiller** [comment]
> Also I'd like to separate the isApplicable to be able to prefilter all plugins

What is the need for prefiltering? I figured the hack would just check the property name or value in `isApplicable`, which will be just as fast as the core doing it.

> Also having just an array of propertyNames and (optional) specific values, will help to keep the code as small as possible, as we only need to parse those once

I don't understand this; which code does it keep as small as possible? Also, why design an API for hacks that wouldn't cover the calc use-case? It's still a common use for prefixing.

> Finally I would rename apply to resolve as we do not really apply the styles but only output the extra/modified version

I just chose `apply` to match `isApplicable` :). "if it is applicable, apply it"

> Passing styles allows us to even resolve/check for multiple properties as mentioned above

Yup, sounds good.

> With an object outputed we can easily use Object.assign to apply those and do not need to loop the array once again

Agree, returning an object is the best way to go.

**Comment by rofrischmann** [comment]
@ianobermiller Hah now I get why its apply :D Also the prefiltering stuff is well, 0,005ms performance perhaps^^ So its just fine to leave that. 

I understand that calc issue (as mentioned above I would solve that using some kind of "global" plugins that get checked on every value), but how would you do e.g. the 2012 flexbox standard I showed above with just one propertyName? Would you have a file for each property? Cause this would 'cause much more code in the end.

**Comment by ianobermiller** [comment]
Yeah I don't think we need any helpers, I like the proposed function that just calls the checks itself. Nice!
