### ISSUE TITLE
Add support for Samsung Browser

### ISSUE THREAD

**Issue by philpl** [rofrischmann/inline-style-prefixer#102]
While the Samsung Browser seems to be just a fork of the stock Android Browser, it doesn't have the same `userAgent`. This is a user Agent from a test device:

```
"Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G900F Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36"
```

I've been able to work around this by adding an exception to when I create the prefixer, that passes user agent as `Android Mobile`, when the actual user agent string contains `SamsungBrowser`.

This might be as simple as adding `[ 'samsung' ]` to the list of android detections.

**Comment by rofrischmann** [comment]
Will try to add this with the next release :)

**Comment by rofrischmann** [comment]
Hmm. My tests do give me `and_chr` browser for this userAgent which seems to be correct right?

Thats: 
Android 6
Chrome 44
prefix: Webkit

**Comment by rofrischmann** [comment]
@philpl Any thoughts on this? Will close for now, but feel free to reopen :P

**Comment by philpl** [comment]
Sorry, for not coming back to you ^^" Maybe I was chasing ghosts here?

**Comment by khanglu** [comment]
Hi @rofrischmann ,

I'm running into an issue on Samsung Internet 4.0, all "display:flex" being prefixed into "display:-webkit-box" which causes some issues.

I believe this prefix is not necessary anymore since display:flex is universally supported in all browser including Samsung Internet ([usage of flex on caniuse.com](http://caniuse.com/#search=flex)).

It would be really appreciated if you can have a look into this. Thank you.

**Comment by rofrischmann** [comment]
@khanglu can you provide the browser information?

```javascript
// on your device
console.log(new Prefixer()._browserInfo)
```

**Comment by khanglu** [comment]
Sure, here it is @rofrischmann 

{
  "name": "Samsung Internet for Android",
  "samsungBrowser": true,
  "version": 4,
  "blink": true,
  "android": true,
  "osversion": 6,
  "mobile": true,
  "a": true,
  "prefix": {
    "inline": "Webkit",
    "css": "-webkit-"
  },
  "browser": "android"
}

**Comment by rofrischmann** [comment]
Great thanks. Would be cool to also see the `userAgent`, forgot about this :P
But I think there's an easy fix for this. But I need more information about the Samsung stock browser.

**Comment by khanglu** [comment]
That's great to hear :) the userAgent is

`Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G930F Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36`
