### ISSUE TITLE
Support custom properties (variables)

### ISSUE THREAD

**Issue by tonygentilcore** [rofrischmann/inline-style-prefixer#106]
It would be awesome to have `var(--foo)` support via something like https://github.com/postcss/postcss-custom-properties

**Comment by rofrischmann** [comment]
Are you sure this has something to do with this prefixer? I don't get the problem actually :/

**Comment by tonygentilcore** [comment]
This may or may not be considered in scope. But the project I linked to let's me write standard [CSS variables](https://www.w3.org/TR/css-variables/) in my `.css` files. Then it inlines the variables for older browsers. For example:

`webpack.config.js`
```js
module.exports = {
  ...,
  postcss: [
    autoprefixer({browsers: ['>5%']}),
    customProperties({variables: theme}),
  ],
}
```

`main.css`
```css
.my-class {
  border: 1px solid var(--myColor)
}
```

With `inline-style-prefixer`, I'd like to similarly be able to use CSS variables in my inline CSS:

```js
const prefixer = new Prefixer({
  userAgent: navigator.userAgent,
  variables: theme
})

const defaultStyle = prefixer.prefix({
  border: '1px solid var(--myColor)',
})
```

**Comment by rofrischmann** [comment]
What you are doing now is considered best practice and mixing weird CSS syntax into inline style is rather uncommon.
Anyways this has nothing to do with the prefixer at all. You could write your own tool to "replace" those values savely.
