### ISSUE TITLE
Fix for #105 is re-ordering styles (even non-prefixed) in different js engines

### ISSUE THREAD

**Issue by alvaroc1** [rofrischmann/inline-style-prefixer#108]
This is mostly a problem when rendering a react component server-side (with nashorn in my case) and then trying to use that on the client side. Since the properties are in a different order, react flags it as a mismatch: 
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
```
This does not happen with version 2.0.4, it only started happening on version 2.0.5.
Checked against:
Nashorn (java 1.8.0_72-b15)
Chrome:  55.0.2883.95 (64-bit)

My guess is some inconsistency between how js engines treat this `Object.keys`, `Object.sort`, or even object property assignment in this code:
https://github.com/rofrischmann/inline-style-prefixer/commit/566dbcf27516eb9f93e8eaaa7aab2330b1a591e4

Not entirely surprising given that object properties are not guaranteed to be in order.

Will see if I can come up with a minimal case and maybe a fix.

**Comment by alvaroc1** [comment]
My guess at this point is because `Object.sort` is not stable: http://stackoverflow.com/questions/3026281/array-sort-sorting-stability-in-different-browsers

Making it stable will probably correct the problem. Will try when I get a chance.

**Comment by rofrischmann** [comment]
Yeah I experienced similar issues. I am currently refactoring the core. (It's going to be 4x faster)
I will remove the sorting, it's probably something library owners need to consider themselves.

**Comment by rofrischmann** [comment]
As the new version does not sort the keys at all, we get rid of the problem within this lib.
