### ISSUE TITLE
userDrag not working

### ISSUE THREAD

**Issue by yspb** [rofrischmann/inline-style-prefixer#109]
import prefixAll from 'inline-style-prefixer/static';

let image = {
      width: '100%',
      userSelect: 'none',
      userDrag: 'none', 
};

image = prefixAll(image);

this converts to:

MozUserSelect:"none"
WebkitUserSelect:"none"
msUserSelect:"none"
userSelect:"none"
userDrag:"none"
width:"100%"

So, disabling drag event is not working in chrome, cause there is no WebkitUserDrag:"none" rule.

**Comment by rofrischmann** [comment]
That's because there is no `user-drag` CSS property. It does not exist right now. There only is the Webkit-specific `-webkit-user-drag` which means you have to use `WebkitUserDrag: 'none'` directly.
