### ISSUE TITLE
Problem with linear-gradient using UserAgent

### ISSUE THREAD

**Issue by lostpebble** [rofrischmann/inline-style-prefixer#111]
```
const titleTextBlockStyle = prefixer.prefix({
    background: `linear-gradient(to top, rgba(${rgbString}, 1) 0, rgba(${rgbString}, 1) 82%, rgba(${rgbString}, 0.4) 84%, rgba(${rgbString}, 0.4) 90%, rgba(${rgbString}, 0.2) 95%, rgba(${rgbString}, 0.1) 100%)`,
});
```

I'm doing some server-side rendering, and I'm having a problem with setting a linear-gradient on an element using the prefixer. Everything else seems to render fine (I assume it's using the UserAgent when doing server-rendering).

I turned off Javascript to see what inline styles are being set on the element from the server rendering, and I see this error in the style inspector:
![lineargradient_error_server_rendering](https://cloud.githubusercontent.com/assets/1508863/21985525/cd9fcffa-dc03-11e6-8c3f-1272361bb3c3.jpg)

Turning it back on, once Javascript has loaded up it corrects itself, and this is what the styles become on that element:
![lineargradient_error_server_rendering_correct](https://cloud.githubusercontent.com/assets/1508863/21985553/f23c1d32-dc03-11e6-90e2-a9e9e83cebd7.jpg)

But that initial paint is coming up blank for my background and its not looking great.

So far I've tested this on Chrome and Firefox, both are outputting the same CSS and giving the same error `Invalid property value`

**Comment by rofrischmann** [comment]
Check this out: https://github.com/rofrischmann/inline-style-prefixer/issues/93
You need to resolve array values yourself to get valid CSS values. This is not done by the prefixer as its up to the user/renderer how those values are applied.

I will add a note to the docs I guess.
