### ISSUE TITLE
Incorrect prefixing linear-gradient (client-side rendering) by Prefixer.prefix

### ISSUE THREAD

**Issue by furagi** [rofrischmann/inline-style-prefixer#119]
I have next snippet:

```
import * as Prefixer from "inline-style-prefixer";
import * as prefixAll from "inline-style-prefixer/static";

const style = {
  display: "flex",
  background: "linear-gradient(top, rgba(137,255,241,0) 50%, rgba(0, 0, 0, 0.5) 100%)",
  userSelect: "none",
}

const prefixer = new Prefixer();
console.log(prefixer._browserInfo)
console.log(prefixer.prefix(style));
console.log(prefixAll(style));
```

Output is next:
```
{
    "name": "Chrome",
    "chrome": true,
    "version": "50.0",
    "blink": true,
    "linux": true,
    "a": true,
    "jsPrefix": "Webkit",
    "cssPrefix": "-webkit-",
    "browserName": "chrome",
    "browserVersion": 50,
    "osVersion": null
}
{
    "display": "flex",
    "background": "linear-gradient(top, rgba(137,255,241,0) 50%, rgba(0, 0, 0, 0.5) 100%)",
    "WebkitUserSelect": "none"
}
{
    "display": ["-webkit-box", "-moz-box", "-ms-flexbox", "-webkit-flex", "flex"],
    "background": ["-webkit-linear-gradient(top, rgba(137,255,241,0) 50%, rgba(0, 0, 0, 0.5) 100%)", "-moz-linear-gradient(top, rgba(137,255,241,0) 50%, rgba(0, 0, 0, 0.5) 100%)", "linear-gradient(top, rgba(137,255,241,0) 50%, rgba(0, 0, 0, 0.5) 100%)"],
    "WebkitUserSelect": "none"
}
```

Looks like Prefixer#prefix doesn't perform css-prefixing, only js (because userSelect was translated to WebkitUserSelect and linear-gradient stays the same). 
As you know, for prefixed properties prefixAll produces an array with results, so, I can't use it with React 15 (even if I will concatenate it to one string).

**Comment by rofrischmann** [comment]
`Prefixer.prefix` doesn't prefix linear-gradient because you don't need it with Chrome 50. That's the whole deal here. The second one is not this libraries problem actually. There're plenty ways to use the array values (e.g. transform to CSS on runtime, using one of the modern CSS-in-JS solutions).

Hope this helps. You can test the gradient prefixing by using an old Chrome userAgent that actually required the prefix.

**Comment by furagi** [comment]
I tested the issue with Chromium-50.0.2661.102 (64-bit), Linux.
This works:
```
background: -webkit-linear-gradient(top, rgba(137,255,241,0) 50%, rgba(0, 0, 0, 0.5) 100%);
```
This doesn't:
```
background: linear-gradient(top, rgba(137,255,241,0) 50%, rgba(0, 0, 0, 0.5) 100%);
```
I've checked with Chrome 43 too:
```
{"name":"Chrome","chrome":true,"version":"43.0","blink":true,"linux":true,"a":true,"jsPrefix":"Webkit","cssPrefix":"-webkit-","browserName":"chrome","browserVersion":43,"osVersion":null}
```
And result is the same.

**Comment by rofrischmann** [comment]
I think the problem is not the prefix, but your gradient itself. I am not a master of gradients as I never use them, but it seems you gradient is old-syntax (which is why it works with prefix).

Try to use the following:
```css
background: linear-gradient(to bottom, rgba(137,255,241,0) 50%, rgba(0, 0, 0, 0.5) 100%);
```

Chrome e.g. dropped the prefix as early as version 25.

**Comment by furagi** [comment]
Yep, you're right, it's because of syntax. Thanks a lot! And sorry for false alarm.
