### ISSUE TITLE
Incorrect prefixing for `display:flex`

### ISSUE THREAD

**Issue by necolas** [rofrischmann/inline-style-prefixer#12]
input
```js
Prefixer({ display: flex })
```
output
```
{
  display: "-webkit-flex;display:flex"
}
```
expected
```
{
  display: "-webkit-flex"
}
```

fwiw, i'm getting webkit prefixes in latest Chrome, even though it supports flexbox without prefixes

**Comment by rofrischmann** [comment]
Hmm, I thought keeping those defaults would be a nice fallback as the browser detection is not 100% precise.
But I will fix the latest chrome issue asap.

**Comment by necolas** [comment]
I agree. It's unfortunate because we can't have multiple `display` values in a single object. I've seen other inline prefixers put fallback display values in the string too. It seems to work for inline styles as they end up as a string in the HTML.

But I am doing some processing on the styles and their values (converting them to classes and CSS string) - https://github.com/necolas/react-native-web/issues/25. The fallback hack tripped up my strategy because the value is not a valid CSS value for `display`. Any alternative ideas to preserve the fallback hack?

**Comment by rofrischmann** [comment]
Oh yeah, I have seen your project and am following its process since then :p 
For sure I could add some kind of preventFallback flag, but I am wondering how you want to solve those values in general as converting into CSS strings won't fix the prefixing jungle.
Is there any special syntax you'd like it to be returned? Maybe an array with fallback values would be easier to handle?

**Comment by ianobermiller** [comment]
It should be easy enough to parse out fallback values by splitting by
semicolon.

I'd say to keep string return as the default, and maybe have the option to
return an array. It would be nice for plugins/hacks to return an array of
values.

**Comment by rofrischmann** [comment]
@ianobermiller Yep, I would say having an array could benefit in other places as well. I am accepting arrays for fallbacks within [react-look](https://github.com/rofrischmann/react-look) and as far as I know, [Radium](https://github.com/FormidableLabs/radium) supports that as well, right? Seems to be the common solution to that.

I am going to refactor the whole code to a far more clean and flexible base. Then I will try to fix some browser detection issues. There're still enough userAgents that are not detected correctly.

**Comment by necolas** [comment]
Sounds good. In my react-native-web `StyleSheet` branch, my styles cache uses arrays of values for each property, so I can determine every declaration the app needs written to a CSS stylesheet. Looking through the code here, I'm having to do similar work to get to a point where I can generate inline styles or a CSS stylesheet from the underlying, nested style data. (I'd prefer not to parse declarations out of values as that is drifting into CSS parsing territory.)

**Comment by rofrischmann** [comment]
Fine then. I will push an implementation asap tomorrow as I am going to bed now (greets from germany :full_moon: )

**Comment by rofrischmann** [comment]
Should now only output: `display: flex`.

If using older webkit browsers it will just output `display: -webkit-flex`.
