### ISSUE TITLE
Should caniuse-api be a dependency?

### ISSUE THREAD

**Issue by oliviertassinari** [rofrischmann/inline-style-prefixer#121]
I ended-up installing `caniuse-api` to make the `inline-style-prefixer/generator` module works.

**Comment by rofrischmann** [comment]
Yeah I think so! Forgot to add that as I got it installed locally anyways. Thanks :) Feel free to PR

**Comment by oliviertassinari** [comment]
I won't have time for it. I wanted to raise that concern in case someone else might have it. It's linked to https://github.com/callemall/material-ui/pull/6343. Thanks for you hard work here!

**Comment by rofrischmann** [comment]
I guess I'll add it as a peerDep. Installing th whole caniuse-api is a mess for basic users. Only ppl using the generator should need to download that beast :P

**Comment by necolas** [comment]
FWIW, I experienced this problem too. Might be worth considering re-supporting older browsers by default for a while longer

**Comment by rofrischmann** [comment]
@necolas @oliviertassinari Would it be fine to just add the install note to the docs? I feel bad to install that for every user

**Comment by necolas** [comment]
Sure

**Comment by jumoel** [comment]
Perhaps this should have been put in [`optionalDependencies`](https://docs.npmjs.com/files/package.json#optionaldependencies) instead?

Libraries like `aphrodite` depend on `inline-style-prefixer` but only uses the generator in a build step, so now a warning appears about unmet peer dependencies for every `aphrodite` user.

**Comment by Rhywden** [comment]
It also appears as a warning for everyone using Material-UI. Just a tad annoying.
