### ISSUE TITLE
Concatenated prefixed css properties doesn't work

### ISSUE THREAD

**Issue by hampusohlsson** [rofrischmann/inline-style-prefixer#123]
Hey @rofrischmann 

Indirectly using your library though [nachoaIvarez/flexbox-react](https://github.com/nachoaIvarez/flexbox-react). Seems to be [an issue](https://github.com/nachoaIvarez/flexbox-react/issues/24) the with way display properties are prefixed when using server side rendering. It used to be supported but apparently dropped in React 15. See https://github.com/facebook/react/issues/9166

![css error](https://cloud.githubusercontent.com/assets/675092/23976671/ab3daf24-09bf-11e7-8c2d-6e43ac40ae27.png)

Any way of fixing this? I'll be happy to PR if you point me in the right direction

**Comment by rofrischmann** [comment]
Refer to https://inline-style-prefixer.js.org/docs/guides/ResolvingArrays.html

There's no way to actually solve this for inline style, but rather by generating some CSS here. Not sure if React will ever solve this. 

Another way is to check if the browser supports the value (one by one) and choose the first one that fits.

Apart from that, I am not sure what else we could do library-side.

**Comment by hampusohlsson** [comment]
Got it.. yeah it's not very clear what is the right approach here. I'm using server side rendering which makes it harder as I don't have a UA
