### ISSUE TITLE
position: -webkit-sticky not working in safari 10

### ISSUE THREAD

**Issue by stefvhuynh** [rofrischmann/inline-style-prefixer#126]
When I write the following code, I don't get the `-webkit-` prefix.
```
const Prefixer = require('inline-style-prefixer');
// With safari version 10.1
const prefixer = new Prefixer({ userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30' });

console.log(prefixer.prefix({ position: 'sticky' })); ==> { position: 'sticky' }
```
However, when the user agent is set to `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/9.3.2 Safari/603.1.30`, I get the correct output (`position: -webkit-sticky`).

EDIT: The above is true of inline-style-prefixer versions under 3. For the latest version, I'm not getting `position: -webkit-sticky` for any version of safari.

**Comment by rofrischmann** [comment]
Can you please tell me the result of `prefixer._browserInfo`? Would be great to know that, because the plugin is build to prefix every `position: sticky` if Safari is detected.
