### ISSUE TITLE
support for yandesbrowser

### ISSUE THREAD

**Issue by omryr** [rofrischmann/inline-style-prefixer#127]
Hi i have issues when using yandexbrowser, im using your library through Radium.

when trying to load my website all the flex tags are not used so if something should be display: 'flex'
it wont appear in the browser.

yandex is built on top of chromium.

adding 'yandexbrowser' to webkit in vendorprefixes and to chrome array in browsers fixed most of the problems.

is there any way you could add support for it?

**Comment by neemah** [comment]
Yes, it would be awesome, Yandex Browser user agent:
`userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.137 YaBrowser/17.4.1.718 Yowser/2.5 Safari/537.36`

It's chrome-based browser.

<img width="1079" alt="yandex-browser" src="https://cloud.githubusercontent.com/assets/212695/26053479/aa73f4f4-3971-11e7-9e7c-1beb6159da24.png">

**Comment by rofrischmann** [comment]
Can someone tell me the output of `new Prefixer()._browserInfo` for a Yandex browser? Yandex information is not shipped via caniuse, so I can't crawl feature support versions or anything, but we might pretend to be Chrome 0 to simply add all webkit prefixes.

**Comment by omryr** [comment]
do you mean this?
 "{"name":"Yandex Browser","yandexbrowser":true,"version":17.4,"blink":true,"mac":true,"a":true,"prefix":{"inline":"Webkit","css":"-webkit-"},"browser":"chrome","osversion":null}"

**Comment by rofrischmann** [comment]
Do you have an example how e.g.
```javascript
const style = {
  display: 'flex',
  flex: 1,
  justifyContent: 'flex-start'
}
``` 
is prefixed with a Yandex browser? It seems like it is already recognized as a Webkit-based browser...

**Comment by omryr** [comment]
adding flex gave me this: {
-webkit-box-align: stretch;
-webkit-box-direction: normal;
-webkit-box-orient: vertical;
}

**Comment by rofrischmann** [comment]
Ok got it. Looks like it detects the old flexbox spec while we would need to use the new one. We can force it to use the new one, but that might crash old Yandex versions. There's no other way to do it apparently, as we do not have a version mapping for those Yandex features on caniuse.
