### ISSUE TITLE
caniuse-api as a PeerDependency

### ISSUE THREAD

**Issue by everdimension** [rofrischmann/inline-style-prefixer#128]
I wonder why you have `caniuse-api` declared as a [peerDependency](https://github.com/rofrischmann/inline-style-prefixer/blob/e64cf7c5ab23ac9e58efe51fe174629ce5df9a49/package.json#L45).

Is there a certain reason why consumers of your package might want to provide this dependency on their own instead of you adding it as a dependency to your project?

**Comment by yamafaktory** [comment]
Hi, I'm also getting this from *Yarn*:
```sh
yarn install v0.22.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "inline-style-prefixer@3.0.3" has unmet peer dependency "caniuse-api@^1.5.2".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
```

**Comment by myknbani** [comment]
Wondering about this as well.

**Comment by rofrischmann** [comment]
Going to remove that soon. Only ppl building their own instance will actually need it :)

**Comment by rofrischmann** [comment]
Released a new version

**Comment by everdimension** [comment]
Great, thanks!!
