### ISSUE TITLE
Supporting legacy syntax?

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/inline-style-prefixer#13]
Should determine if legacy syntax should be supported and resolved as well.
e.g. all those different `linear-gradient` specs. Just take a look at http://www.colorzilla.com/gradient-editor/

Sure those should be prefixed to work properly at all. But also there is a different syntax within e.g. the old webkit version which would be broken if using a new syntaxed linear-gradient.
 
@ianobermiller @necolas Would be great to have an opinion on this.
I would say yes, we should do that, but it would enlarge the whole output file as well.

**Comment by ianobermiller** [comment]
What kind of support does using only the latest syntax get us? Might be good enough by now.

**Comment by rofrischmann** [comment]
Well as far as I know, it would just drop some old versions of safari, chrome (and perhaps other webkit-based), but that shouldn't affect at all, as most chrome & safari users tend to update more common the others.

But I was asking myself why we should support all flexbox specs, but then drop e.g. linear-gradient. 
Problem is that this is not just "inline-style-prefixing" but also style normalization, which might fit a whole new project if respecting every browser difference.

**Comment by ianobermiller** [comment]
I'd say if autoprefixer does it, it falls under the auspices of and inline style prefixer as well.

Based on caniuse, http://caniuse.com/#feat=css-gradients, it looks like everything except older android supports the latest syntax.

**Comment by necolas** [comment]
at work we support IE 10+. that will be IE 11+ pretty soon. webkit for safari and android 4.x. i think getting too crazy about prefixing support in the browser is not ideal. this library is already quite big with all the compatibility data included. so i'd be in favour of reducing the amount of compatibility data (does anyone need a prefixed border-radius inline style on the client?).

**Comment by rofrischmann** [comment]
@necolas I think e.g. IE 9 is still a big deal for many clients, but for sure no one needs a prefixed border-radius anymore. How would you suggest to do that? We could have some kind of config file which defines the minimum browser version to support, but that would again lead to running some kind of build script on client side again.

**Comment by necolas** [comment]
Easy first step could be to define a baseline of support this library provides and only import the data needed to meet it. e.g. "IE 9+, Safari 6+, Android 4+, ...". I wouldn't worry about consumer configuration at this stage.

**Comment by rofrischmann** [comment]
@necolas I will take that in consideration. I will also have some kind of config though, so ppl who (somehow) need to support IE8 or sth. like that, still have the option to do that via a custom build. 

I got everything ready to be released, but will have to test some parts again. After the exam tomorrow I will try to add that.

**Comment by rofrischmann** [comment]
I was able to save around 3kb by removing some very old browsers. Removing `object-assign` for a simple object assign fix (as it is only pasting in a key) would again safe around 1kb.

Then we could check if there is any difference within safari & ios_saf at all (which affects the prefixer). Merging those could again safe 2kb.

**NOTE**: I am always talking about compressed files only. Not doing any zipping here.

**Comment by necolas** [comment]
sounds good. thanks

**Comment by ianobermiller** [comment]
Yeah, I think it would be pretty easy to strip a whole bunch of stuff out of bowser; we don't care about identifying obscure browsers. Maybe republish as bowser-lite and keep it up-to-date?

**Comment by necolas** [comment]
and react native's subset of css means most of the properties needing prefixes aren't supported yet. might be nice to support them in a web version, but i'd also like to keep the prefixing code we use as small as possible. thanks for this.

**Comment by rofrischmann** [comment]
Let's start by decreasing the package size to a minimum. Then we might also split into different packages (one for web and one for native). 
Actually it has ~7kb gzipped. Let's try to get under 3 ;)

**Comment by rofrischmann** [comment]
Let's specify the following browser versions:
```
chrome: 30+
android: 4+
ios/safari: 6+
firefox: 25+
ie/ie mobile: 9+
opera: 13+
opera mini: 5+ 
android UC: 9+
```

Also ich will merge ie/ie Mob to one as well as ios/safari. Perhaps also merge android chrome and android into one.

**Comment by rofrischmann** [comment]
Will close this one as it is now configurable using the `config.js` file
