### ISSUE TITLE
Prefixing `backface-visibility` property

### ISSUE THREAD

**Issue by rtkhanas** [rofrischmann/inline-style-prefixer#130]
I'm not using this module directly, but using `styled-components` and I found it depends on this one. I noticed there are no prefixes for `backface-visibility` property, which is not supported in Safari without a `-webkit` prefix.

I may try to dig into this module and add this somehow when I find some free time, but if some of you who knows this project can add it - would be great.

Thank you.

**Comment by rofrischmann** [comment]
Hmm thats strage. I am not sure how styled-components uses the prefixer directly, but by checking my data I can see that I list `backfaceVisibility` as a prop to be prefixed with `-webkit-`

**Comment by rtkhanas** [comment]
I opened a similar issue in `styled-components` and got a response: https://github.com/styled-components/styled-components/issues/878#issuecomment-306815033
