### ISSUE TITLE
Prefixing for electron

### ISSUE THREAD

**Issue by dacz** [rofrischmann/inline-style-prefixer#131]
Hi, thanks for your great lib. I'm considering to use it in electron. Is there any way how I would be able to specify something like 'target' as 'electron'?
Thanks a lot.

**Comment by rofrischmann** [comment]
Doesn't it work with Electron? Should be detected as Chrome-like and prefixed with Webkit stuff

**Comment by dacz** [comment]
What I meant is to have `browserlist: ...` definition in `package.json` write inline styles and let inline style prefixer do its best... (maybe after telling it that it should pick the list from).

**Comment by rofrischmann** [comment]
Hmm, thats exactly how it works right? You can create your own prefixer if you want to customize the browserList, but we do not have a electron key, because caniuse does not list electron.

**Comment by dacz** [comment]
ah. sorry for my ignorance. I did not see this in the docs. I like to hear that. Thanks.

**Comment by necolas** [comment]
FWIW, I think the default prefixer should have better cross-browser support. Users who have extreme bundle size requirements or only target a subset of browsers could build their own custom prefixers (rather than the other way around).
