### ISSUE TITLE
Incorrect legacy values for display: inline-flex

### ISSUE THREAD

**Issue by necolas** [rofrischmann/inline-style-prefixer#132]
This is the result I get when using the static prefixer on `inline-flex`:

```
display:-webkit-box;
display:-moz-box;
display:-ms-inline-flexbox;
display:-webkit-inline-flex;
display:inline-flex
```

It looks like it should be producing `-webkit-inline-box` and `-moz-inline-box`.

**Comment by rofrischmann** [comment]
Oh I see. Funny that this never occured before :o Seems like noone is using `inline-flex` nowadays. I will fix that immediately :)

**Comment by necolas** [comment]
Thanks
