### ISSUE TITLE
prefixed properties appear after non-prefixed versions

### ISSUE THREAD

**Issue by threepointone** [rofrischmann/inline-style-prefixer#133]
via https://github.com/threepointone/glamor/issues/298, it appears that prefixed properties for flexGrow and flexShrink appear *after* the non prefixed props. is this expected behaviour? please, and thank you for a kickass package!

**Comment by rofrischmann** [comment]
Yeah thats true. It shouldn't be a problem as long as the prop doesn't change behavior with prefixes. We once had prop ordering baked in, but object property ordering was kind of hard as there were multiple platform incompatibilities.
Yet I see that this might be a valid use case. How about adding a utility to `css-in-js-utils` which you can explicitly import and use?
(We also removed it in terms of performance as its basically another object property iteration.

**Comment by threepointone** [comment]
I'll close this issue, assuming it doesn't cause any real problems. I'll open up a new one if something arises, and I'll likely work on a workaround from my end, will share when I have something. thank you!
