### ISSUE TITLE
Flex basis for IE

### ISSUE THREAD

**Issue by kasrakoushan** [rofrischmann/inline-style-prefixer#134]
Hi! Currently the style prefixer uses `msPreferredSize` for `flexBasis`, but IE does not accept this property. Instead it should be `msFlexPreferredSize`. See the property in the IE inspector below:
<img width="419" alt="ms-flex-properties" src="https://user-images.githubusercontent.com/10523155/28543396-721e1726-7074-11e7-9501-a613cb79c597.png">

Thank you!

**Comment by rofrischmann** [comment]
Feel free to send a PR to fix it :) The place to look for it is in plugins/flexboxIE in both /static and /dynamic

**Comment by kasrakoushan** [comment]
Thank you! I've made a PR here: https://github.com/rofrischmann/inline-style-prefixer/pull/135 😃
