### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by ahz** [rofrischmann/inline-style-prefixer#136]
FYI I've created types definitions for TypeScript into https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18413

**Comment by rofrischmann** [comment]
Cool! Thank you :) We might add a link to the README, would you like to send a PR for that?

**Comment by ahz** [comment]
Yes, I will do that once the PR would be merged and released as npm package...

**Comment by TedDriggs** [comment]
@rofrischmann would you be open to a PR which moves this into inline-style-packager using the [`types` property in `package.json`](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)?

**Comment by rofrischmann** [comment]
Sure! Go for it =)
