### ISSUE TITLE
Use a proper browser detection tool

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/inline-style-prefixer#14]
As bowser takes almost half of the gzipped output file, we should focus on reducing that by using a more lightweight library that only provides/parses information we actually need.

**Comment by ianobermiller** [comment]
I was looking at the bowser code, and I didn't see a whole lot that we could actually remove unless we explicitly drop support for non-mainstream browsers.

**Comment by rofrischmann** [comment]
Hmm. Maybe I will check that out and even delete those tiny things. Then we might also kick the getBrowserInformation method this repo uses (which is some kind of validating the bowser output to modify the information => should not need this later on)

**Comment by rofrischmann** [comment]
Seems that the caniusedata is still the biggest file at all. The flexbox plugins are quite fat too, but removing them would kill flexbox for IE10 and a lot of older webkit-based ...

**Comment by rofrischmann** [comment]
Will tackle this issue starting next week. Should bring some extra byte reduction :tada:

**Comment by rofrischmann** [comment]
As for now its not quite easy to get there. Have started experimented but sadly some userAgents even do not follow given rules at all. As by introducing the `prefixAll` fallback, this should be done later perhaps, if at all.
