### ISSUE TITLE
Static and dynamic plugins for old flexbox are not equivalent

### ISSUE THREAD

**Issue by necolas** [rofrischmann/inline-style-prefixer#153]
The static plugin for old flexbox is missing some of the features of the dynamic plugin, which means it doesn't provide the same browser compatibility

**Comment by rofrischmann** [comment]
Do you have detailed information, which parts are missing?
The default static prefixer is configured to support IE >= 11, so e.g. die IE flexbox fixes are not included in the default static version. The dynamic prefixer on the other hand checks the browser version via user-agent, so it might still add the IE stuff if an IE < 11 is provided.

You can also create your own static version with a different browser version range (see the docs).
If apart from that, inconsistence still exists, I am more than happy to fix it :P

**Comment by necolas** [comment]
@lyahdav patched the missing `flexGrow` in the plugin in this branch https://github.com/lyahdav/inline-style-prefixer/commits/3.0.8-flexbox-old-fixes. Comparing the plugins suggests there may be some other differences in functionality

**Comment by lyahdav** [comment]
Yup, the change I made in my fork was needed to support Android < 4.4 browser. Also I had to use the dynamic prefixer instead of static because of other things that are missing from the static prefixer flexboxOld plugin.

**Comment by rofrischmann** [comment]
Can anybody elaborate on missing differences that should be added as well? Going to release some fixes soon and want to add those!

**Comment by lyahdav** [comment]
Take a look at this branch on my fork: https://github.com/lyahdav/inline-style-prefixer/commits/3.0.8-flexbox-old-fixes

Also compare the flexboxOld plugin under static vs dynamic folders in your main repo.

**Comment by rofrischmann** [comment]
Alright, I just added those changes as well. Next time, I'd appreciate a PR to add that directly 🙈

**Comment by rofrischmann** [comment]
Just released 4.0.2 including those changes :)
