### ISSUE TITLE
Can't resolve 'inline-style-prefixer/static' in Can't resolve 'inline-style-prefixer/static' in 

### ISSUE THREAD

**Issue by rahillakhani** [rofrischmann/inline-style-prefixer#163]
ERROR in ./Can't resolve 'inline-style-prefixer/static' in 
Module not found: Error: Can't resolve 'inline-style-prefixer/static' in '/Users/rahil/Docs/projects/O2/MyO2_Payg/content/payg/node_modules/narcissus/build'
 @ ./~/narcissus/build/generate.js 14:14-53
 @ ./~/narcissus/build/index.js
 @ ./~/react-modal-dialog/lib/FlexDialog.js
 @ ./~/react-modal-dialog/lib/index.js
 @ dll vendor

facing this issue from today, static folder is missing - breaking change

**Comment by rofrischmann** [comment]
That's why we released a new major version.
Check out the Changelog and the docs to see what changed.
