### ISSUE TITLE
backdrop-filter is not -webkit prefixed

### ISSUE THREAD

**Issue by necolas** [rofrischmann/inline-style-prefixer#164]
A newer CSS property that requires a webkit prefix for Safari

https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter

**Comment by rofrischmann** [comment]
Hmm, as you can see here: https://unpkg.com/inline-style-prefixer@5.0.1/lib/data.js

We also prefix backdropFilter using the `Webkit` prefix. Can you show me a use case where this doesn't happen? Just tested it locally and it worked.
