### ISSUE TITLE
unneeded gitbook-plugin-prism dependency (npm lib potentially out of sync with git repo)

### ISSUE THREAD

**Issue by pcooney10** [rofrischmann/inline-style-prefixer#169]
I noticed in `5.0.3` that there's a dependency for `gitbook-plugin-prism` that should really be in `devDependencies`. It seems like this was addressed in #168, but was somehow reverted since.

I would make a PR to update this, but it seems the npm library (latest is 5.0.3) is ahead of this repo (5.0.2 in package.json, and no `gitbook-plugin-prism` in dependencies).

Thanks !

**Comment by rofrischmann** [comment]
I just pushed the 1.0.3 code and it seems that it's not part of the deps anymore which makes me curious why npm still shows that... Will have a new release soon anyways, so it should be fixed by then :)
