### ISSUE TITLE
Add hacks to handle browser differences

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/inline-style-prefixer#2]
For e.g. there are 4 official flexbox specifications untill the draft was finalized. This is not really a prefixer issue but should also be included as Autoprefixer does, too. 
Also there are some value differences e.g.
```CSS
display: -webkit-box;
display: -moz-box;
display: -ms-flexbox;
display: -webkit-flex;
display: flex;
```

**EDIT**: As @ianobermiller pointed out nicely, it is kind of of easy to add alternative values. Therefore the following known browser issues need to be implemented:
- [x] **Flexbox** (see [DSS-Flexbox Processor](https://github.com/dynamicstylesheets/DSS-Flexbox))
 - Android < 4.4 `-webkit-box`, ...
 - IE 10 `ms-flex-`...
- [x] **cursor**
 - `zoom-in`, `zoom-out`, `grab`, `grabbing` for WebKit and Firefox
- [x] **gradients**
- [x] **Intrinsic & Extrinsic Sizing**

More will eventually be added later

**Comment by ianobermiller** [comment]
Defining a property multiple times may not be possible with plain javascript, but it is possible with React's handling of style:

```js
display: '-webkit-flex;display:flex'

**Comment by rofrischmann** [comment]
@ianobermiller Damn, I never knew that :D thanks a lot, this will safe some time for sure!

**Comment by rofrischmann** [comment]
Also if this we use this syntax we should probably rename it to react-style-prefixer as it d be only useful for React by now

**Comment by ianobermiller** [comment]
React and any other tool that serializes a style object to a string to then stick in the style property.

**Comment by rofrischmann** [comment]
Oh ok, thought they'd attach those directly, then I will instantly rename it again 😅

**Comment by rofrischmann** [comment]
Closed as support has been added fully
