### ISSUE TITLE
Remove IE < 11 support on April 11, 2017

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/inline-style-prefixer#20]
:tada: :tada: 
Microsoft will drop support for any Internet Explorer < Version 11 (IE9 & IE10).
We should remove those instantly.

**Comment by ianobermiller** [comment]
Only on the latest OS:

> The company continues to support IE9 on Vista (and Windows Server 2008), and will do so until support for Windows Vista ends on April 11, 2017

**Comment by rofrischmann** [comment]
Oh noooo :sweat_smile: well so I'll switch that. 2017 is coming

**Comment by rofrischmann** [comment]
@ianobermiller What about this? https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

**Comment by ianobermiller** [comment]
As in the earlier comment, IE9 is still supported for Vista users: https://support.microsoft.com/en-us/lifecycle#gp/Microsoft-Internet-Explorer. That being said, usage has dropped below 1%, and will stop being supported by major websites soon. Can you quantify the burden or amount of code that is just for IE9 and IE10?

**Comment by rileyjshaw** [comment]
@ianobermiller the entire [plugins folder](https://github.com/rofrischmann/inline-style-prefixer/tree/master/modules/plugins) is about 5kb, not sure how much of that is strictly for old IE.

For what it's worth, we officially dropped IE9 at Khan Academy a couple of days ago. It sounds like IE10 support will stick around in the industry for quite a while, though... :P

**Comment by rofrischmann** [comment]
Version 3.0.0 will drop IE < 11 for bundle size reasons. We will have a new way to configure custom prefixer instances without cloning the repository.
