### ISSUE TITLE
keyframes support

### ISSUE THREAD

**Issue by ianobermiller** [rofrischmann/inline-style-prefixer#21]
Not sure what the API would look like, but it'd be nice if inline-style-prefixer could provide the prefix (if any) required for `@keyframes`. I am trying to get Radium 100% server-side-render-friendly, and keyframes is the last one getting in the way.

**Comment by rofrischmann** [comment]
Oh sure. That's something essential. How do you handle your keyframes? I know you define them with a helper using only the frames e.g. 
```javascript
wrapper({
   '50%': {
      ...
   }, 
   '100%': {
      ...
   }
}, component)
```
But is there an actual stage where you got something like:
```javascript
{
   '@keyframes foo': {
      // frames
   }
}
```
If so we could easily add those :P

**Comment by ianobermiller** [comment]
No, there is no point at which we have such an object; keyframes are handled separately from normal styles, mainly because they are typically global and reused across the app. In order to avoid tying `inline-style-prefixer` to a specific non-standard form of the style object, perhaps we just expose keyframes as a separate API, say `Prefixer.getKeyframesAtRule`?

**Comment by rofrischmann** [comment]
Yeah I think this should not be part of the main module to keep it simple. Could you provide an example? Anyways you're free to push a proposal as I am not deeply into keyframes at all^^

**Comment by ianobermiller** [comment]
I was thinking something like this:

```
const prefixer = new Prefixer();
prefixer.prefixedKeyframes === '-webkit-keyframes';

**Comment by rofrischmann** [comment]
Oh well, if that's the only thing, I'll let it happen with the next release. Today :)
