### ISSUE TITLE
Error occurs when navigator doesn't exist

### ISSUE THREAD

**Issue by Beingbook** [rofrischmann/inline-style-prefixer#22]
`inline-style-prefixer/lib/Prefixer.js:43:46` occurs `TypeError: Cannot read property 'CSS' of undefined`

<img width="414" alt="2015-11-10 10 36 03" src="https://cloud.githubusercontent.com/assets/2682865/11076107/4fab223c-883c-11e5-9f0d-7b821027eb0e.png">

I edited it below and works correctly.
<img width="437" alt="2015-11-10 10 31 16" src="https://cloud.githubusercontent.com/assets/2682865/11076106/4f7ff1b6-883c-11e5-933a-2763cfff54f9.png">

Can it be hot-fixed? I expect to update it as soon..

**Comment by Webkadabra** [comment]
+1

**Comment by ianobermiller** [comment]
You must either have navigator present or pass a userAgent. We should
probably do that validation and throw an error early to make this more
obvious.

**Comment by rofrischmann** [comment]
@Beingbook As @ianobermiller mentioned, you should either have a navigator present or (if doing server-side rendering) pass an userAgent to the constructor, but I will add a warning asap to prevent that issue. Thanks for reporting!
