### ISSUE TITLE
Bad UA gives TypeError: Cannot read property 'CSS' of undefined

### ISSUE THREAD

**Issue by ianobermiller** [rofrischmann/inline-style-prefixer#24]
If inline-style-prefixer can't handle the userAgent, the constructor throws. We should probably instead return some default object that doesn't do anything.

```
TypeError: Cannot read property 'CSS' of undefined
   at new Prefixer (/Users/iano/dev/radium/node_modules/inline-style-prefixer/lib/Prefixer.js:43:46)

**Comment by ianobermiller** [comment]
Just saw #23, let me update to the newest version and see if it is fixed.

**Comment by rofrischmann** [comment]
Oh well, I was just checking if there is a userAgent provided. Not if it is valid :/ 
Will fix that later at home, at university right now :p

**Comment by rofrischmann** [comment]
@ianobermiller Now checking for valid userAgents, if the agent is not support it justs warns and will not add any prefixes.

@oliviertassinari This should fix all the problems occuring within Material-UI. I'd recommend updating to the latest version and fixing the prefix implementation as it is no longer possible to create a new Prefixer instance with the userAgent set to '*'. You should use the static method `Prefixer.prefixAll` if no userAgent was provided.

**Comment by oliviertassinari** [comment]
@rofrischmann Thanks, I'm gonna update material-ui with this change!
