### ISSUE TITLE
Unsopported browser

### ISSUE THREAD

**Issue by oliviertassinari** [rofrischmann/inline-style-prefixer#25]
Hi, we have this weird issue https://github.com/callemall/material-ui/issues/2159. I'm wondering if this could be because of an unsupported browser and no fallback.

Same for this https://github.com/callemall/material-ui/issues/2119. Shouldn't we fallback to something if the browser can't be match?

**Comment by oliviertassinari** [comment]
Oups, duplicate of https://github.com/rofrischmann/inline-style-prefixer/issues/24

**Comment by rofrischmann** [comment]
Hey @oliviertassinari Yeah I have noticed that too. I will be fixing this today, but I'd be really helpful to have browser information to see why it fails :P Seems like bowser does not match every userAgent out there.
