### ISSUE TITLE
Support of flexWrap

### ISSUE THREAD

**Issue by oliviertassinari** [rofrischmann/inline-style-prefixer#27]
I can't see flexWrap in the supported properties list. 
Is this supported and if not why?

Related https://github.com/callemall/material-ui/pull/2248

**Comment by rofrischmann** [comment]
@oliviertassinari Now that you mention it.. Seems like I missed that one.
You can see all props [here](https://github.com/rofrischmann/inline-style-prefixer/blob/master/generator/searchMap.js) with their referencing caniuse-data keyword as key.
I will add this and update the prefixer today.

**Comment by oliviertassinari** [comment]
Perfect, thanks.
