### ISSUE TITLE
IE9 support (specifically transform)

### ISSUE THREAD

**Issue by Mosho1** [rofrischmann/inline-style-prefixer#30]
The main page says IE9 is supported, but I don't see the -ms- prefix on IE9, or when rendering on the server using an IE9 user agent.

**Comment by rofrischmann** [comment]
What prefixes do you expect to see / which properties do you want to get prefixed? Actually (according to caniuse.com) IE 9 only supports prefixed `transform` and `transformOrigin` (as well as `transformOriginX`, `transformOriginY`).

**Comment by Mosho1** [comment]
As far as I know (and see in the browser), IE9 and IE10 need the `-ms-` prefix for `transform`. However, it's not on the browser [list ](https://github.com/rofrischmann/inline-style-prefixer/blob/master/dist/prefixer.js#L236).

**Comment by rofrischmann** [comment]
Ah right, actually this got fixed 2 days ago (see closed issues) this will be published on npm tomorrow :p

**Comment by Mosho1** [comment]
Cool, thanks!
