### ISSUE TITLE
SeaMonkey flex prefixing

### ISSUE THREAD

**Issue by marudor** [rofrischmann/inline-style-prefixer#31]
Hey,

Using the latest SeaMonkey flex style get prefixed with -moz. SeaMonkey uses the same Rendering Engine as Firefox and can only handle flex without prefixing.

**Comment by rofrischmann** [comment]
Hey @marudor 

As you see in the README, we do not officially support SeaMonkey for the reason that it is not listed on caniuse.com.
Right now I am just mapping it to a -moz prefix which might cause the issue as it does not match the firefox versions? For now I will just remove it completely to not encounter unwanted prefixes.

If we want to support SeaMonkey (and other firefox-based) we need to have a correct mapping of SeaMoney version => Firefox version to determine which prefixes are needed.

**Comment by marudor** [comment]
I think removing SeaMonkey would be enough for now.
I can't really find Information about prefixes for SeaMonkey. But as the non Prefix support of Gecko is quite good it does solve some problems.
