### ISSUE TITLE
Typo in caniuseData

### ISSUE THREAD

**Issue by kings0c** [rofrischmann/inline-style-prefixer#32]
animationIterationCount is typo'd as anmationIterationCount for some reason.

Will have look into this tomorrow :+1:

**Comment by rofrischmann** [comment]
Woops, Have never tested this property by now :/ 
Thanks again for that report and thanks again for fixing it soon?

**Comment by kings0c** [comment]
haha, been a bit busy last couple of days. Will take a look when I can ^^

**Comment by rofrischmann** [comment]
@kings0c I just quickfixed it, will be published with the end of this week
