### ISSUE TITLE
Support passing array of user agents to prefix for multiple browsers

### ISSUE THREAD

**Issue by emilecantin** [rofrischmann/inline-style-prefixer#34]
I'd like to pre-render some mostly static React pages, and serve them from S3. Because I don't know the user-agent at render time, I'd like to pre-render with all (or some of) the vendor prefixes set. Is that possible?

**Comment by emilecantin** [comment]
Sorry, just saw this: https://github.com/rofrischmann/inline-style-prefixer/blob/master/src/Prefixer.js#L29
> Pass an asterisk as userAgent to combine all prefixes

Still, I think it might be useful to pass an array of user agents if I only want, say, Firefox and Chrome but not IE. The above solves my use-case, though. Want me to close the issue?

**Comment by rofrischmann** [comment]
Hmm. Now that you mention it, I have to update the code documentation as the asterisk is no longer supported.
You'd use the static prefixAll method.
```javascript
import Prefixer from 'inline-style-prefixer'
Prefixer.prefixAll(/* styles */)
```

We might think about multiple userAgents, but I'd probably just use multiple prefixer? e.g.
```javascript
import Prefixer from 'inline-style-prefixer'

const ChromePrefixer = new Prefixer(/* Chrome userAgent */)
const FirefoxPrefixer = new Prefixer(/* Firefox userAgent */)

let styles = {/* styles */}
ChromePrefixer.prefix(styles)
FirefoxPrefixer.prefix(styles)
```
Or is there any advantage for using multiple userAgents with one prefixer which I do not know?

**Comment by doctyper** [comment]
> I have to update the code documentation as the asterisk is no longer supported.

Hm, that's disappointing. We are fronting our requests via a CDN which strips out unique headers such as user agents. I was hoping to use the asterisk feature to work around this limitation.

We are using a React + Radium stack, I don't believe Radium supports a way to use `prefixAll`.

**Comment by rofrischmann** [comment]
@doctyper Hmm. Perhaps I will quickly create a radium-prefix-all plugin to handle this as I do not want to mix this up again. Was a bit confusing with both the single and the asterisk userAgent in one single prefix method.

**Comment by emilecantin** [comment]
Yeah, my use case is through Radium too, so if it can work through a plugin, I'd be happy :smile:

**Comment by rofrischmann** [comment]
@doctyper @emilecantin Gimme 12 hours and I'll publish it :)

**Comment by rofrischmann** [comment]
Here you go: [radium-plugin-prefix-all](https://github.com/rofrischmann/radium-plugin-prefix-all)
Note the **Warning** in the README :P

**Comment by ianobermiller** [comment]
Woot, first plugin not made by me afaik :)

**Comment by emilecantin** [comment]
That's great @rofrischmann ! Thanks a lot!

**Comment by rofrischmann** [comment]
@ianobermiller Haha! I am proud to be first one to publish a radium plugin :smile_cat: 
@emilecantin You're welcome
