### ISSUE TITLE
A few properties prefixed wrongly on Edge

### ISSUE THREAD

**Issue by kumarharsh** [rofrischmann/inline-style-prefixer#35]
I was browsing through the source code of my website, and saw that Radium had prefixed the flex properties differently:

```css
align-items: center;
justify-content: center;
```

was changed to
```css
-webkit-align-items: center;
-webkit-justify-content: center;
```

Edge supports the unprefixed properties out of the box, so I think this prefixing is not needed.

**Comment by rofrischmann** [comment]
Hey @kumarharsh, assuming that webkit prefixed get applied, it seems that bowser return the wrong browser information which sadly is nothing I can influence by now.

I will add a keep fallback functionality tomorrow to solve this issue for now. As soon as my custom detection tool ships, this will be resolved.

**Comment by kumarharsh** [comment]
@rofrischmann no probs. Actually, Edge correctly applies even the webkit styles (although I believe that can change in the future, and is not the *correct* behaviour anyways). So, it's not a huge problem, but I thought I'd report it anyways to get it covered.

**Comment by rofrischmann** [comment]
Thanks for that effort :) I remember reading something about Edge supporting both -ms- and -webkit- prefixes. That might be the reason why it still works, but ofc we should try to remove those completely as they're not required and might be removed soon.
