### ISSUE TITLE
ignoring userAgent warning when testing the app

### ISSUE THREAD

**Issue by LeoAJ** [rofrischmann/inline-style-prefixer#36]
HI

I used `Radium` in my react app and I am writing karma unit test for my app, every time I run the test it will show the warning like this:

![screen shot 2015-12-08 at 4 03 44 pm](https://cloud.githubusercontent.com/assets/492921/11672520/31ab79ea-9dc6-11e5-8c67-b42893a52be0.png)

Obviously I knew the userAgent is not valid, since it is running by karma. I tried to set env to production but it is not working either. But eventually it is not a solution, because it is dev process not production level.

Thus, is there a way I can skip this warning while running the unit testing? Thanks!

**Comment by ianobermiller** [comment]
https://github.com/FormidableLabs/radium/tree/master/docs/faq#how-can-i-get-rid-of-useragent-warnings-in-tests

**Comment by LeoAJ** [comment]
Thanks! That is exactly what I need, I appreciated.

**Comment by rofrischmann** [comment]
Thanks for that fast response! @ianobermiller
