### ISSUE TITLE
Default value option

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/inline-style-prefixer#39]
As https://github.com/rofrischmann/inline-style-prefixer/issues/38#issuecomment-168415157 would like to have a fallback option, we should perhaps reimplement those. Default prefixing can just be done with keeping the old (unprefixed) property. 
Plugins might need to apply alternative string props (`display: '-webkit-flex;display:flex'`)

**Comment by rofrischmann** [comment]
Fully supported now!

**Comment by kylefinley** [comment]
That was fast.

Thanks @rofrischmann

**Comment by rofrischmann** [comment]
You're welcome :)
