### ISSUE TITLE
disableWarnings option

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/inline-style-prefixer#42]
Rather than maintaining a whitelist of browsers (which therefore still needs to be supported by bowser either) we might add a disableWarnings option for e.g. headless browser testing and test in general.
Still this should only be used with caution and for tests **only**. 
The warnings are a quite useful "feature" for us to detect unknown browsers and this increases with the number of users.
We could also refactor the warning method from `process.env.NODE_ENV !== 'production'` to `process.env.NODE_ENV === 'development'`. Now one could call the tests using a  `NODE_ENV=test`. This again would perhaps cause problems with other libraries so I would rather go with option 1 if at all.

**Comment by ianobermiller** [comment]
Is the whitelist too much of a burden? I'd think after a few reports, we'd be able to cover 99% of cases with a few UAs.

**Comment by rofrischmann** [comment]
Yeah actually I do not know. I think it would be a bit easier for ppl to understand so that there are less issues opened concerning this case especially. I do not know what all the headless browsers and test environments use as a userAgent (if they use a DOM mock at all). 
Perhaps we should just add another line of warning that tells how to disable those if only testing. That might help as well.

Right now I need more time to gather information on all the userAgent's which is barely there hehe :P Im not always thinking a lot while opening issues, but it helps me to remember and manage all the ideas and issues on several projects.

**Comment by rofrischmann** [comment]
I'd say we just add whitelisted browsers by demand. I really do not need those and also do not see the problem with some warnings in the console or some test environment.
