### ISSUE TITLE
Isomorphic apps

### ISSUE THREAD

**Issue by bmamouri** [rofrischmann/inline-style-prefixer#43]
When using inline-style-prefixer in isomorphic app, the userAgent is undefined.

Is there any solution for this problem? [This article](http://reactjsnews.com/isomorphic-react-in-real-life/) suggests using `less` to solve the problem.

**Comment by ianobermiller** [comment]
The latest version of Radium support server rendering for media queries, keyframes, and has proper prefixing. Check out the example for more info [1], and I plan to write up a blog post about it soon, or at least publish a minimal repo.

[1] https://github.com/FormidableLabs/radium/blob/master/examples/server.js

`inline-style-prefixer` works just fine on the server, you just have to pass the `userAgent` from the request headers.

**Comment by bmamouri** [comment]
Thanks! This exactly solved my problem. Since I use react-router I needed to put it into a wrapper. For those who are reading this in future, check this page out: https://github.com/FormidableLabs/radium/issues/429

**Comment by rofrischmann** [comment]
As this problem was solved I will close the issue. I also put some basic info into the FAQ now.
