### ISSUE TITLE
Wrong display:flex prefix on older Android (4.2.2) running new version of Chrome (47.0.2526.83)

### ISSUE THREAD

**Issue by hburrows** [rofrischmann/inline-style-prefixer#45]
Using version 0.6.2.  I'm running Chrome 47.0.2526.83 on an older version of Android (4.2.2).  The userAgent as reported by `navigator.userAgent` is "Mozilla/5.0 (Linux; Android 4.2.2; Galaxy Nexus Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Mobile Safari/537.36".

When I prefix `{display: 'flex'}` it returns  `{ display: '-webkit-box' }` which Chrome doesn't recognize.  Should prefix as `-webkit-flex` or just not prefix at all.

To reproduce:

```
var Prefixer = require('inline-style-prefixer');
var prefixer = Prefixer({userAgent: "Mozilla/5.0 (Linux; Android 4.2.2; Galaxy Nexus Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Mobile Safari/537.36"})
prefixer.prefix({display: 'flex'})
{ display: '-webkit-box' }
```

**Comment by rofrischmann** [comment]
Thanks for reporting! I actually figured out the issue. Will fix this asap

**Comment by hburrows** [comment]
Well... thanks for the great library and being so responsive in fixing this issue
