### ISSUE TITLE
`Prefixer.prefixAll({display: 'flex'})` yields unexpected output

### ISSUE THREAD

**Issue by rileyjshaw** [rofrischmann/inline-style-prefixer#50]
Based on the [Browser Support](https://github.com/rofrischmann/inline-style-prefixer#browser-support) list, I'd expect `Prefixer.prefixAll({display: 'flex'})` to yield:

```
  display: -webkit-box;
  display: -moz-box;
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex;
```

The output that I'm getting is:

```
  display: -webkit-box;
  display: flex;
```

Is this intentional?

**Comment by rofrischmann** [comment]
Seems like we forgot to also use the "prefixAll" for the special plugins. Let me add this soon.
