### ISSUE TITLE
Use warning instead of warn to reduce the output size

### ISSUE THREAD

**Issue by oliviertassinari** [rofrischmann/inline-style-prefixer#56]
Having a look at how `warn` is used, you noticed that the error message will not be removed by uglify.
We are using https://github.com/oliviertassinari/babel-plugin-transform-dev-warning in the `material-ui` repository to get complement rid of the warning check in production.

**Comment by rofrischmann** [comment]
Seems legit :) would you mind sending a pull request?

**Comment by oliviertassinari** [comment]
You are using babel@5 (https://github.com/rofrischmann/inline-style-prefixer/blob/master/package.json#L43). Do you plan to upgrade to v6? Otherwise this is the plugin to use: https://github.com/4Catalyzer/babel-plugin-dev-expression.

> would you mind sending a pull request?

Why not. It's only used twice, that may be overkill :grin:

**Comment by rofrischmann** [comment]
Yeah I am slowly migrating all my repo as I touch them the next best time. Well still its used twice :P I also want to use this for all my repos, so why not include it everywhere :P I'll perhaps notify you or just include it myself after I upgraded :P
