### ISSUE TITLE
[prefixAll] no working as expected with transition: transform

### ISSUE THREAD

**Issue by oliviertassinari** [rofrischmann/inline-style-prefixer#57]
I was playing with the `prefixAll` functionnality on `material-ui`. I have noticed various issues with this function.
Here is the first one:
```jsx
const style1 = inlineStylePrefixer.prefixAll({
  transform: 'translate3d(0, 0, 0)',
  transition: 'transform 400ms cubic-bezier(0.23, 1, 0.32, 1) 0ms',
  WebkitTapHighlightColor: 'rgba(0,0,0,0)',
  backgroundColor: '#ffffff',
  borderRadius: '50%',
  bottom: 24,
  boxShadow: '0 3px 10px rgba(0, 0, 0, 0.16), 0 3px 10px rgba(0, 0, 0, 0.23)',
  boxSizing: 'border-box',
  display: 'inline-block',
  fontFamily: 'Roboto, sans-serif',
  position: 'fixed',
  right: 24,
});

....

<div style={style1}>Hello</div>
```

All the styles after `transition` are not applied correctly to the `div` element:
![capture d ecran 2016-01-23 a 23 14 11](https://cloud.githubusercontent.com/assets/3165635/12533144/154d6ff8-c227-11e5-98fa-f4e67a436392.png)

**Comment by rofrischmann** [comment]
Would be more than pleased to get all other issues as well. I will check those tomorrow, then we can add tests for those cases too @oliviertassinari

**Comment by rofrischmann** [comment]
Oh of course I got it. I am splitting multiple transitions at every `,` and totally forgot that this totally freaks out when using `cubic-bezier`. This should be easy to fix.

**Comment by rofrischmann** [comment]
@oliviertassinari Right now you could seperate your `transitionTimingFunction` to get it working, but I will hopefully release a fix later today :P

**Comment by oliviertassinari** [comment]
Awesome, thanks.

> Would be more than pleased to get all other issues as well.

Sure, I need to find some time to find reproductible example.
I know that one was related to `calc(...%*)`.

**Comment by rofrischmann** [comment]
@ianobermiller @oliviertassinari recommend updating to 0.6.7, otherwise it breaks prefixing multiple transitions that use a cubic-bezier.
