### ISSUE TITLE
[prefixAll] Throw Can't find variable: Symbol

### ISSUE THREAD

**Issue by oliviertassinari** [rofrischmann/inline-style-prefixer#58]
That's linked to https://github.com/rofrischmann/inline-style-prefixer/blob/master/modules/utils/getBrowserInformation.js#L37.
Any reason for not using `Object.keys(prefixKeys).forEach(prefix => {`?

**Comment by rofrischmann** [comment]
Hmm yeah we could do that, but you should need a Symbol polyfill anyways if you're using React or am I wrong?

**Comment by oliviertassinari** [comment]
> but you should need a Symbol polyfill anyways if you're using React or am I wrong?

I don't know, but I would say no according to https://github.com/callemall/material-ui/pull/2904.

**Comment by oliviertassinari** [comment]
> Hmm yeah we could do that

Awesome, I'm gonna submit a PR. I need this to be fixed :grin:

**Comment by rofrischmann** [comment]
I just always happen to see Symbols in every React element, but perhaps they only use those if they're available. But ofc, its no problem to change that.

Btw. you could also use https://github.com/rofrischmann/radium-plugin-prefix-all to use the `prefixAll` with Radium (just saw your pull request at radium :P)

**Comment by oliviertassinari** [comment]
> Btw. you could also use https://github.com/rofrischmann/radium-plugin-prefix-all

Oh, I wasn't aware of this plugin!

**Comment by rofrischmann** [comment]
Yeah, actually it is not listed anywhere. We should add a list of third-party plugins to the radium docs perhaps. cc @ianobermiller
