### ISSUE TITLE
Either the global navigator was undefined or an invalid userAgent was provided.

### ISSUE THREAD

**Issue by SPAHI4** [rofrischmann/inline-style-prefixer#60]
Error with Yandex Browser

**Comment by rofrischmann** [comment]
As written in the Readme, we only support common browser. Could you give me some more information on Yandex? Which engine is it based on, which prefixes does it need, what does a example userAgent look like?

**Comment by SPAHI4** [comment]
@rofrischmann https://udger.com/resources/ua-list/browser-detail?browser=Yandex.Browser

**Comment by immuzov** [comment]
Same warning with Yandex Browser.

**Comment by pidov** [comment]
Running into the same issue while trying to test (using jsdom) components from https://github.com/callemall/material-ui/

My test helper: 
```javascript
import jsdom from 'jsdom';
const doc = jsdom.jsdom('<!doctype html><html><body></body></html>');
const win = doc.defaultView;

global.document = doc;
global.window = win;

Object.keys(window).forEach((key) => {
  if (!(key in global)) {
    global[key] = window[key]
  }
})
```

If I try to set custom userAgent like so: 

```javascript
const doc = jsdom.jsdom('<!doctype html><html><body></body></html>', {
  userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36'
});
```

I'm running into another issue. The custom user agent conflicts with ReactDOM, as the later is trying to use `console.debug` which throws an error in node:

```
console.debug('Download the React DevTools for a better development experience: ' + 'https://fb.me/react-devtools');
TypeError: console.debug is not a function
...
```

Basically a deadlock

**Comment by necolas** [comment]
why throw an error if a UA isn't known?

**Comment by rofrischmann** [comment]
I guess this has nothing to do with this issue in general. It issues support for Yandex Browser at all, which remains even if we remove the UA warning, so let's take this to another issue.

@SPAHI4 I am sorry to tell, that by now and without any further information on Yandex's need for prefixes in relation to its versions, we can not support it. This prefixer is build on data from the caniuse.com API and therefore only capable of those browser listed in the README.
I will close this for now.
