### ISSUE TITLE
Consider removing the unknown userAgent warning

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/inline-style-prefixer#62]
We might consider removing the warning at all. This would remove the need of a whitelist and remove the need to "simulate" a valid userAgent.

Also note that at some point the warning is used to file detection bugs as well. One would perhaps wonder why styles do not get prefixed correctly which is where the warning often helped to understand the problem.

**Comment by irvinebroque** [comment]
I'd be in favor of at least allowing it to be removed -- currently, if you use JSDOM as a test environment, this warning is thrown in tests because the user-agent is `Node.js (darwin; U; rv:v5.5.0)`.

Related -- my expectation is that if the user agent cannot be parsed for any reason, the prefixer will fallback to use [prefixAll](https://github.com/rofrischmann/inline-style-prefixer#prefixerprefixall-static).

**Comment by rofrischmann** [comment]
Yeah, I also got those warnings within my tests (but basically just ignore those). As I still think removing is kind of a bad idea, using `prefixAll` as a fallback gives pretty much sense. 

Still I'd like to think more about that the next couple days. I am happy to see other feedback and thanks @irvinebroque !

**Comment by chriswalkr** [comment]
Would be really good to get a way to disable this warning, makes running unit tests awkward.

**Comment by AdamBoxall** [comment]
+1

Personally I don't think the code should log anything when it doesn't recognise a user-agent. Also not everyone uses a fake DOM that spoofs the UA, so I wouldn't log anything then, either.

**Comment by rofrischmann** [comment]
I guess providing the `prefixAll` fallback actually also removes the need for a warning as the warning was used to tell "Hey, you might end up with broken (as unprefixed) styles in some browsers."
I think we can also upgrade to 1.0 after this is implemented as it then supports basically* every browser.

* Of course there still might be a case where the detection tool fails and returns wrong browser data which leads to wrong prefixing, but that's nothing we can change or should focus on.
