### ISSUE TITLE
pull fix for camelCased properties in prefixAll

### ISSUE THREAD

**Issue by Swatinem** [rofrischmann/inline-style-prefixer#63]
I’ve just ran into the same problem with prefixAll that creates camelCased properties for gradients, which has already been fixed in the fork here:

https://github.com/Khan/inline-style-prefixer/commit/f41f3040ac27eeec3b7a1fb7450ddce250cac4e4

would be nice if you could pull that fix and make a release :-)

**Comment by rofrischmann** [comment]
I already asked for a pull request and was told that will happen soon :)
