### ISSUE TITLE
Add support for tap-highlight-color

### ISSUE THREAD

**Issue by oliviertassinari** [rofrischmann/inline-style-prefixer#64]
Could we add the support for the `tap-highlight-color` property?
At first, I thought that it would be a good idea to not use it, but as pointed out by @owencm https://github.com/callemall/material-ui/issues/3410#issuecomment-186968242.
That would be better to handle it.

**Comment by rofrischmann** [comment]
Do you have any information when and which prefixes are needed? We sure can add everything, but caniuse does not provide anything so I guess we add it manually. 

As far as I know it **must** be prefixed with `-webkit-` as it is an unofficial feature right?

**Comment by oliviertassinari** [comment]
> but caniuse does not provide anything

As far as I'm aware, it should only be prefixed with `-webkit-`. Well, I'm not sure how official this feature is and if it's going to stay in the long run.
The other option for Material-UI is to manually add the prefix.
I'm wondering what's best here.

**Comment by rofrischmann** [comment]
Hmm. Yeah, as it is not an official part of the CSS specs and does not work unprefixed anyways, you should perhaps use the prefixed version yourself. But ofc we can also add that, it still is a property that needs a prefix :P

**Comment by oliviertassinari** [comment]
> should perhaps use the prefixed version yourself

I agree. Let's stay coherent with https://github.com/callemall/material-ui/pull/2946/files and close this issue. Thanks.

**Comment by rofrischmann** [comment]
Heh, I was just about to suggest that I also treat sth. like `overflow-scrolling` the same way.
Seems like the "best" solution I guess.

**Comment by oliviertassinari** [comment]
What do you mean, do you want to handle `overflow-scrolling` here too?

**Comment by rofrischmann** [comment]
Oh no sry, I meant that I myself also manually add the prefix for other unsupported props like overflow-scrolling.
Or in general, any property that is not planned to ever exist unprefixed.

**Comment by oliviertassinari** [comment]
Alright, looks like we both agree :+1:.
