### ISSUE TITLE
Display property getting dropped

### ISSUE THREAD

**Issue by rynti** [rofrischmann/inline-style-prefixer#65]
I've noticed that the display property is getting dropped with certain user agents, see [this example](https://gist.github.com/rynti/673095c92971fdcfa4a0).

Not only the iPhone 4 user agent in the example is affected, here's a list of a few others:

**Amazon Kindle Fire HDX:** `Mozilla/5.0 (Linux; U; en-us; KFAPWI Build/JDQ39) AppleWebKit/535.19 (KHTML, like Gecko) Silk/3.13 Safari/535.19 Silk-Accelerated=true`

**Samsung Galaxy Note 3:** `Mozilla/5.0 (Linux; U; Android 4.3; en-us; SM-N900T Build/JSS15J) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`

**Samsung Galaxy Note II:** `Mozilla/5.0 (Linux; U; Android 4.1; en-us; GT-N7100 Build/JRO03C) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`

**Samsung Galaxy S III:** `Mozilla/5.0 (Linux; U; Android 4.0; en-us; GT-I9300 Build/IMM76D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`

**Internet Explorer 10:** `Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0`

I understand that this library doesn't support certain old browsers, which is why I don't expect any prefixing for them, but I would rather like to see no changes than the display property getting removed :laughing: Additionally, most other properties do seem to work (i.e. marginTop). Anyone have an idea as to why is this happening and how it can be fixed?

**Comment by rofrischmann** [comment]
Really interesting one. So it drops the `display` completely instead of "just" not prefixing it? I will investigate further tomorrow when trying to push all new changes discussed here.
