### ISSUE TITLE
Prefix all by default when browser is not matched

### ISSUE THREAD

**Issue by AdamBoxall** [rofrischmann/inline-style-prefixer#67]
Version 48 of Chrome (on Android) was released recently, but because that particular version is unknown in "caniuse" right now, this library defaults to not prefixing any properties. Obviously this causes display issues with properties that still do require a prefix.

I think the best default here would be to apply the vendor's prefixes, even if the browser version can't be matched?

**Comment by rofrischmann** [comment]
This is already done in the newest develop version, but I am still waiting for a PR to push 1.0.0.
Will update soon
