### ISSUE TITLE
Display property getting dropped in IE10

### ISSUE THREAD

**Issue by pdc** [rofrischmann/inline-style-prefixer#69]
I am using Material UI and its buttons become invisible on IE10. This is because they have lost their `inline-block` display property. It is present in the `styles` property but disappears when `prepareStyles` is applied to it.

I think this is because the `flexboxIE` plugin has a similar loop to that addressed in other browsers in  #65: if I understand the code correctly, the `properties` variable has `display` in it so it is replaced, but `altProperties` has no entry for `display` so it is replaced with nothing.

(When I say IE10 I actually mean IE11/Edge in its IE10-emulation mode running on Windows 8.1.)

**Comment by rofrischmann** [comment]
Hey @pdc. This has already been fixed as you can see here:
https://github.com/rofrischmann/inline-style-prefixer/blob/master/test/prefixer-test.js#L337
I assume material-ui did not update the prefixer yet. You might ask them to do :)

**Comment by pdc** [comment]
Thanks for the quick response! You're right, Material UI is still using 0.6.6...
