### ISSUE TITLE
Error when trying to use version 1.0.0 with radium

### ISSUE THREAD

**Issue by chriswalkr** [rofrischmann/inline-style-prefixer#73]
Hello, I've been trying to upgrade [radium](https://github.com/FormidableLabs/radium) to use version 1.0.0 of your library with  however doing so and running the radium tests gives me the following errors:
```
START:
08 03 2016 10:09:35.544:INFO [karma]: Karma v0.13.21 server started at http://localhost:8080/
08 03 2016 10:09:35.553:INFO [launcher]: Starting browser PhantomJS
08 03 2016 10:09:36.385:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket /#FoTscCSsKMIAWLOIAAAA with id 57301862
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: Set
  at /Users/cwa21/radium/src/__tests__/enhancer-test.js:20600
```

It looks like maybe inline-style-prefixer or inline-style-prefixer-all isn't distributing using babel properly? I've spent a while investigating this but I've hit a bit of a wall. I've managed to get the tests to run if I use an es5 shim for PhantomJS into their karama tests but that doesn't seem to be good solution.

Do you have any pointers or ideas?

**Comment by rofrischmann** [comment]
In fact, I am using ES2015 `Set` to do faster lookups for properties (compared to array/object). Babel though does not transpile `Set`. As far as I learned it is considered best practice to provide polyfills with a library but rather let the users choose their own.

So if you're adding e.g. [es6-set](https://www.npmjs.com/package/es6-set) before your tests, everything should work as expected. 
I guess this is worth pointing out in the README directly. I kind of forgot about that, thanks!

**Comment by rofrischmann** [comment]
I guess this solved the problem, if not feel free to reopen.
