### ISSUE TITLE
Invalid User Agent.

### ISSUE THREAD

**Issue by dardub** [rofrischmann/inline-style-prefixer#77]
I'm getting a warning for invalid user agent. 

`Either the global navigator was undefined or an invalid userAgent was provided. Using a valid userAgent?`

This application is for ps4 web application. The user agent string is:

<Removed>
Let me make sure its okay to display the UA string.
A pretty old version of Webkit.

Thanks.

**Comment by rofrischmann** [comment]
Could you please provide further information which userAgent you're using and which prefixes you expect to see? I got no idea what ps4 actually needs, but I guess this is not sth. this prefixer will cover as the information is not provided by caniuse. You might check out [inline-style-prefix-all](https://github.com/rofrischmann/inline-style-prefix-all)

**Comment by rofrischmann** [comment]
Closing this as we do not support PS4 and no further information was provided.
