### ISSUE TITLE
Incorrect Chrome support for cursor: grab

### ISSUE THREAD

**Issue by alexyaseen** [rofrischmann/inline-style-prefixer#79]
As far as I can tell, cursor.js is checking for chrome < 37 to decide whether to prefix 'grab' and 'grabbing'. However, even on Chrome 50 I'm seeing the need to still prefix 'grab' and 'grabbing'.

**Comment by rofrischmann** [comment]
Do you have any information which browser need prefixes for `grab` and `grabbing`?
I can't find any serious links and as it seems caniuse.com now only list `zoom-in` and `zoom-out` which had the `grab` and `grabbing` listed within the same group before.
Seems like we need a new plugin in that case.

**Comment by alexyaseen** [comment]
I haven't found a reliable source for which browser needs the prefixes. I'm seeing the same as you on caniuse.com. Always prefixing those values might not be a great approach, but perhaps better than nothing for now?

**Comment by rofrischmann** [comment]
Yeah I guess that would be great, we should have both plugins. One for zoom-in / zoom-out one for those grab cursor. Waiting for your PR :)
