### ISSUE TITLE
Pass userAgent as parameter instead of stateful setter

### ISSUE THREAD

**Issue by ianobermiller** [rofrischmann/inline-style-prefixer#8]
What do you think about eliminating module level state required by `Prefixer.setUserAgent` and instead allowing you to optionally pass the userAgent to `Prefixer.process`?

I recently converted Radium to be (mostly) stateless, moving all configuration to passed in parameters instead of module-level variables and setters, and find it easier to test and reason about in general. Additionally, it is safer for server-side environments (less potential for leakage) and overall easier to get right (never have to reset, for example).

**Comment by rofrischmann** [comment]
This sounds fair to be considered as I also work on a more stateless version of Look right now. As said, I will start again on wednesday. Till then, thanks for your effort!

**Comment by rofrischmann** [comment]
Closed as this was pushed earlier :)
