### ISSUE TITLE
[prefixAll] inverse prefix order in server-side

### ISSUE THREAD

**Issue by oliviertassinari** [rofrischmann/inline-style-prefixer#80]
The output of the following code is no longer the same when doing **server side rendering**.
The output is completely different. That's breaking the style of the element.
```js
import InlineStylePrefixer from 'inline-style-prefixer';

InlineStylePrefixer.prefixAll({...});
```
E.g. for a `display: flex` property, let's compare the output:
- before: `display:-webkit-box;display:-moz-box;display:-ms-flexbox;display:-webkit-flex;display:flex`
- now: `display:flex,-webkit-flex,-ms-flexbox,-moz-box,-webkit-box` 

I suspect that it's the commit responsible for this **regression**: https://github.com/rofrischmann/inline-style-prefix-all/commit/545af4f31c7ee24f19656242010821e5a0cd9746

- inline-style-prefixer: v1.0.3
- React: v0.15.0

**Comment by oliviertassinari** [comment]
@rofrischmann Are you sure about your fix?
The output is now `display:-webkit-box,-moz-box,-ms-flexbox,-webkit-flex,flex;`.
The values are in the right order, but they still miss the `display:`.
I'm missing something?

**Comment by rofrischmann** [comment]
As the prefix-all module now returns arrays of fallback values, you need to join them on your own to get the correct string. This was done because React 15+ can't handle fallback stringd actually.
I will implement this for all other plugins within this module soon.

**Comment by oliviertassinari** [comment]
> This was done because React 15+ can't handle fallback strings actually.

I though it was react-dom. Isn't react-server still able to do it? I may be wrong.
Thanks, I will try this path.
