### ISSUE TITLE
Incorrect prefixing display:flex

### ISSUE THREAD

**Issue by maciejmyslinski** [rofrischmann/inline-style-prefixer#83]
Hello!
I am using [material-ui](https://github.com/callemall/material-ui). It takes advantage from inline-style-prefixer. I discovered bug related to inline-style-prefixer, though. [Take a look at this](https://github.com/callemall/material-ui/issues/4280).
Could you help somehow? What could we fix in inline-style-prefixer to improve this project?
Thanks 👍 
Maciej

**Comment by rofrischmann** [comment]
As I've commented on the original post (because it might be helpful for material as well), I will close this one.
