### ISSUE TITLE
_utilsCapitalizeString2.default is not a function

### ISSUE THREAD

**Issue by luckyraul** [rofrischmann/inline-style-prefixer#85]
Here https://github.com/rofrischmann/inline-style-prefixer/blob/master/dist/prefixer.js#L153
I got an error 

```Uncaught TypeError: (0 , _utilsCapitalizeString2.default) is not a function```

look for reference https://github.com/callemall/material-ui/issues/4361

**Comment by rofrischmann** [comment]
Hmm, it seems like the dist build is broken... I have not tested this one for quite some time, Ill try to fix it today
