### ISSUE TITLE
Chromium browser triggers `invalid userAgent` warning

### ISSUE THREAD

**Issue by bobholt** [rofrischmann/inline-style-prefixer#88]
Using [Chromium](http://www.chromium.org/) Version 50.0.2661.102 Built on Ubuntu 14.04, running on LinuxMint 17.3 (64-bit)

The U/A string is `"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/50.0.2661.102 Chrome/50.0.2661.102 Safari/537.36"`

**Comment by rofrischmann** [comment]
This has already been fixed with https://github.com/rofrischmann/inline-style-prefixer/pull/86 I guess. Check back today for a new release fixing this :P
