### ISSUE TITLE
Prefixer removes multiple/fallback values

### ISSUE THREAD

**Issue by Swatinem** [rofrischmann/inline-style-prefixer#89]
When specifying multiple values, like this:
`{ position: [ 'fixed', 'sticky' ] }`
only the first alternative is kept after prefixing:
`{ position: 'fixed' }`

**Comment by rofrischmann** [comment]
@Swatinem Are you using the dynamic or the `/static` version?
@rtsao Could this be an issue with your array prefixing PR?

**Comment by Swatinem** [comment]
Yes, this happened when I was switching from `inline-style-prefix-all` to `inline-style-prefixer/static`.

**Comment by rtsao** [comment]
If it worked in `-all` (my PR) it must be some change that occurred when moving to this repo

**Comment by rofrischmann** [comment]
well `prefix-all` does not include your PR on npm. I merged that when moving to `/static`. I got no idea why we should have removed array values before as I did not iterate those at all. But ofc it was just an idea as you actually did this array prefixing recently :P

**Comment by rtsao** [comment]
Oh, didn't realize it was never published. Probably should remove it then until a failing test case can be added and bug resolved.

**Comment by rofrischmann** [comment]
@rtsao Are you talking about removing the array prefixing? I will have a look at that tomorrow. I believe we should keep array prefixing if possible :P

**Comment by rofrischmann** [comment]
I both fixed the array prefixing and also added array prefixing to the dynamic `new Prefixer().prefix`. Feel free to update to 2.0.1 :P
