### ISSUE TITLE
Facilitate user generated prefix data

### ISSUE THREAD

**Issue by nathanmarks** [rofrischmann/inline-style-prefixer#90]
It would be great if the package came with a generator in `bin` to create the prefix data specifically for the browsers that the user wants to target. This way we can leave out things like old Safari versions for example that require a lot of prefixes.

**Comment by oliviertassinari** [comment]
Notice that there is already kind of a *standard* way to declare the targetted browser : [browserslist](https://github.com/ai/browserslist).

**Comment by rofrischmann** [comment]
I guess I can push something next week, but I'd prefer to use hardcoded versions as its much simpler to use with the current API I guess. So you basically pass an object similar to the `config.js` and get a set of prefix properties :P

**Comment by jaydenseric** [comment]
Ideally the static version would share [the autoprefixer behavior](https://github.com/postcss/autoprefixer#browsers), in that it would accept a browserslist config or look for a browserslist file.

**Comment by rofrischmann** [comment]
This will be built-in in version 3.0.0. Documentation is on its way :P
