### ISSUE TITLE
Why does inline-style-prefixer/static produce invalid CSS?

### ISSUE THREAD

**Issue by AndersenTobias** [rofrischmann/inline-style-prefixer#93]
`prefixAll` produces

```css
display: flex, -webkit-flex, /* ... omitted ... */
```

which is invalid CSS and ignored by Chrome.
The way to solve this is with

```javascript
const outputStyles = {
  display: 'flex; display: -webkit-flex; display: ...'
}
```

Am I missing something?

**Comment by rofrischmann** [comment]
Heyhey, I recommend reading: https://github.com/rofrischmann/inline-style-prefixer/issues/91
It should answer your question. I will yet add some hint to the README as it is not without saying that you need to resolve those arrays.

You might check how Fela's [fallbackValue](https://github.com/rofrischmann/fela/blob/master/modules/plugins/fallbackValue.js) plugin  resolves the values.
