### ISSUE TITLE
Firefox 48.0 on Android 4.2 is detected as Firefox 4.2

### ISSUE THREAD

**Issue by realcr** [rofrischmann/inline-style-prefixer#95]
I tracked down an issue in Radium:
https://github.com/FormidableLabs/radium/issues/815
To an issue with inline-style-prefixer.

Observed behaviour:
```
userAgent("Mozilla/5.0 (Android 4.2.2; Mobile; rv:48.0) Gecko/48.0 Firefox/48.0").version === 4.2
```

Expected behaviour:
```
userAgent("Mozilla/5.0 (Android 4.2.2; Mobile; rv:48.0) Gecko/48.0 Firefox/48.0").version === 48.0
```

I think that the problem is at:
https://github.com/rofrischmann/inline-style-prefixer/blob/master/modules/utils/getBrowserInformation.js

As Bowser parses this user agent string correctly.

**Comment by rofrischmann** [comment]
Yeah. Was not aware ppl use Firefox on Android. (I actually never touched an Android phone by now)
I will have to add an additional check for firefox. Thanks @realcr

**Comment by rofrischmann** [comment]
Will close this one. New version will be released today!

**Comment by realcr** [comment]
Thank you!
