### ISSUE TITLE
Windows Phone 10.0 Edge will fallback to prefix all.

### ISSUE THREAD

**Issue by steinarn** [rofrischmann/inline-style-prefixer#97]
On Windows 10.0 Mobile with Edge 
(UserAgent "Mozilla/5.0 (Windows Phone 10.0;  Android 6.0.1; Nokia; Lumia 520) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Mobile Safari/537.36 Edge/14.14348") getBrowserInformation will return browser = "ie_mob". _usePrefixAllFallback will then be set to true (Prefix.js line 64), result: eg display: flex will be prefixed and not be read by Edge.

If I move ['windowsphone', 'mobile', 'msedge'], ['windowsphone', 'tablet', 'msedge'] from "ie_mob" to "edge" (edge: [['msedge'], ['windowsphone', 'mobile', 'msedge'], ['windowsphone', 'tablet', 'msedge']], getBrowerInformation.js) everything renders correctly.

Tested on (with components from material-ui.com):
* Windows 10 Edge with Emulation set to: Browser profile: Windows 10 Mobile, User agent string: Microsoft Edge 
* Windows 10 Mobile Emulator - Edge - https://developer.microsoft.com/en/windows/downloads/sdk-archive

**Comment by rofrischmann** [comment]
Ill check that later this week, but it seems like you already got the fix. Thanks! @steinarn
