### ISSUE TITLE
unsupported UserAgent for Yandex.Browser

### ISSUE THREAD

**Issue by dpvlasov-yndx** [rofrischmann/inline-style-prefixer#98]
Yandex browser (https://browser.yandex.com) can have this kind of UserAgents:
on windows - Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 YaBrowser/16.9.0.2763 Yowser/2.5 Safari/537.36 
on mac - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 YaBrowser/16.9.0.2765 Safari/537.36
and http://www.material-ui.com/#/components/app-bar - does not work well with it. 

but if i remove all yandex part (YaBrowser/16.9.0.2763 Yowser/2.5 - for Windows , or  YaBrowser/16.9.0.2765 - for Mac) - it works fine.
<img width="887" alt="material-ui-yabro" src="https://cloud.githubusercontent.com/assets/22001873/18243658/bc7ce9e0-7364-11e6-8764-67258f7b0b03.png">

**Comment by rofrischmann** [comment]
As clearly written in the documentation, we do not support Yandex browser out of the box. I would suggest to use the static version instead. Caniuse.com doe s not provide any information on prefixes used within the Yandex browser.
